src/Entity/Product.php
<?php

namespace App\Entity;

use App\Repository\ProductRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProductRepository::class)]
class Product
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column]
    private ?float $list_price = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $about = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $how_to_use = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $ingredient = null;

    #[ORM\ManyToOne(inversedBy: 'products')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Category $category = null;

    #[ORM\OneToMany(mappedBy: 'product', targetEntity: Gallery::class)]
    private Collection $galleries;

    public function __construct()
    {
        $this->galleries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getListPrice(): ?float
    {
        return $this->list_price;
    }

    public function setListPrice(float $list_price): static
    {
        $this->list_price = $list_price;

        return $this;
    }

    public function getAbout(): ?string
    {
        return $this->about;
    }

    public function setAbout(?string $about): static
    {
        $this->about = $about;

        return $this;
    }

    public function getHowToUse(): ?string
    {
        return $this->how_to_use;
    }

    public function setHowToUse(?string $how_to_use): static
    {
        $this->how_to_use = $how_to_use;

        return $this;
    }

    public function getIngredient(): ?string
    {
        return $this->ingredient;
    }

    public function setIngredient(?string $ingredient): static
    {
        $this->ingredient = $ingredient;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): static
    {
        $this->category = $category;

        return $this;
    }

    /**
     * @return Collection<int, Gallery>
     */
    public function getGalleries(): Collection
    {
        return $this->galleries;
    }

    public function addGallery(Gallery $gallery): static
    {
        if (!$this->galleries->contains($gallery)) {
            $this->galleries->add($gallery);
            $gallery->setProduct($this);
        }

        return $this;
    }

    public function removeGallery(Gallery $gallery): static
    {
        if ($this->galleries->removeElement($gallery)) {
            // set the owning side to null (unless already changed)
            if ($gallery->getProduct() === $this) {
                $gallery->setProduct(null);
            }
        }

        return $this;
    }
    //    My Code
    public function __toString()
    {
        return (string) $this->getId();
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\User;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class)
            ->add('fullname', TextType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/Admin/UserController.php
<?php

namespace App\Controller\Admin;

use App\Entity\User;
use App\Form\UserType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\PasswordHasher\Hasher\UserPasswordHasherInterface;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[IsGranted('ROLE_ADMIN')]
#[Route('/admin', name: 'admin_')]
class UserController extends AbstractController
{
    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('/user', name: 'app_user')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $this->denyAccessUnlessGranted('ROLE_ADMIN');
        $em = $doctrine->getManager();
        $repo = $em->getRepository(User::class);
        $users = $doctrine->getRepository('App\Entity\User')->findAll();
        return $this->render('admin/user/index.html.twig', [
            'users' => $users,
        ]);
    }
    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('/user/edit/{id}', name: 'edit_user')]
    public function editAction(ManagerRegistry $doctrine, $id, Request $request)
    {
        $em = $doctrine->getManager();
        $user = $em->getRepository('App\Entity\User')->find($id);
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $doctrine->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash(
                'notice',
                'User Edited'
            );
            return $this->redirectToRoute('admin_app_user');
        }
        return $this->renderForm('admin/user/edit.html.twig', ['form' => $form, 'id' => $id]);
    }
    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('/user/delete/{id}', name: 'delete_user')]
    public function deleteAction(ManagerRegistry $doctrine, $id)
    {
        $em = $doctrine->getManager();
        $product = $em->getRepository('App\Entity\User')->find($id);
        $em->remove($product);
        $em->flush();

        $this->addFlash(
            'error',
            'User deleted'
        );
        return $this->redirectToRoute('admin_app_user');
    }
    #[IsGranted('ROLE_SUPER_ADMIN')]
    #[Route('/user/reset/{id}', name: 'reset_user')]
    public function resetPasswordAction(ManagerRegistry $managerRegistry, $id, UserPasswordHasherInterface $userPasswordHasher)
    {
        $em = $managerRegistry->getManager();
        $user = $em->getRepository('App\Entity\User')->find($id);
        $user->setPassword(
            $userPasswordHasher->hashPassword(
                $user, '123456'
            )
        );
        $em = $managerRegistry->getManager();
        $em->persist($user);
        $em->flush();
        $this->addFlash(
            'notice',
            'Reset password successfully. User id: '.$user
        );

        return $this->redirectToRoute('admin_app_user');
    }
}

src/Controller/User/AccountController.php
<?php

namespace App\Controller\User;

use App\Form\UserType;
use App\Manager\AccountManager;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use App\Form\ResetPasswordType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/user')]
#[IsGranted('ROLE_USER')]
class AccountController extends AbstractController
{
    #[Route('/account/edit', name: 'edit_user')]
    public function editAction(ManagerRegistry $managerRegistry, Request $request, Security $security)
    {
        $user = $security->getUser();
        $user = $managerRegistry->getRepository('App\Entity\User')->find($user);
        $form = $this->createForm(UserType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $managerRegistry->getManager();
            $em->persist($user);
            $em->flush();

            $this->addFlash(
                'notice',
                'User Edited'
            );
            return $this->redirectToRoute('edit_user');
        }
        return $this->renderForm('user/account/edit.html.twig', ['form' => $form]);
    }
    #[Route('/account/password/change', name: 'change_password')]
    public function changePassword(AccountManager $accountManager,Request $request)
    {
        $form = $this->createForm(ResetPasswordType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $user = $this->getUser();
            $oldPassword = $form->get('oldPassword')->getData();
            $newPassword = $form->get('newPassword')->getData();
            if ($accountManager->changePassword($user, $oldPassword, $newPassword)) {
                return $this->redirectToRoute('app_login');
            } else {
                $this->addFlash('error', 'Invalid old password');
            }
        }

        return $this->renderForm('login/reset_password.html.twig', [
            'form' => $form,
        ]);
    }
}

src/Controller/User/CartController.php
<?php

namespace App\Controller\User;

use App\Entity\Order;
use App\Form\CartType;
use App\Manager\CartManager;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
#[IsGranted('ROLE_USER')]
class CartController extends AbstractController
{
    #[Route('/user/cart', name: 'app_user_cart')]
    public function index(CartManager $cartManager, Request $request): Response
    {
        $cart = $cartManager->getCurrentCart();
        $form = $this->createForm(CartType::class, $cart);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $cart->setUpdatedAt(new \DateTime());
            $cartManager->save($cart);

            return $this->redirectToRoute('app_user_cart');
        }

        return $this->render('user/cart/index.html.twig', [
            'cart' => $cart,
            'form' => $form->createView()
        ]);
    }
    #[Route('/user/checkout', name: 'app_user_checkout')]
    public function checkout(CartManager $cartManager): Response
    {
        // Retrieve the current cart
        $cart = $cartManager->getCurrentCart();
        $cartManager->checkout($cart);

        // Redirect to a success page or another relevant page
        return $this->redirectToRoute('app_user_cart');
    }
}

src/Controller/User/LandingPageController.php
<?php

namespace App\Controller\User;

use App\Entity\Product;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class LandingPageController extends AbstractController
{
    #[Route('/', name: 'app_landing_page')]
    public function index(ManagerRegistry $doctrine): Response
    {   $em = $doctrine->getManager();
        $repo = $em->getRepository(Product::class);
        $products = $repo->findProductShop();
        return $this->render('user/landing_page/index.html.twig', [
            'products' => $products
        ]);
    }
}

src/Controller/User/OrderController.php
<?php

namespace App\Controller\User;

use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;

#[Route('/user')]
#[IsGranted('ROLE_USER')]
class OrderController extends AbstractController
{
    #[Route('/order', name: 'user_order')]
    public function showOrderAction(ManagerRegistry $doctrine, Security $security): Response
    {
        $em = $doctrine->getManager();
        $orders = $em->getRepository('App\Entity\Order')->findBy(['user' => $security->getUser()]);
        return $this->render('user/order/index.html.twig', [
            'orders' => $orders,
        ]);
    }
    #[Route('/order/view/{order_id}', name: 'user_order_view')]
    public function showOrderItemAction(ManagerRegistry $doctrine, $order_id): Response
    {
        $em = $doctrine->getManager();
        $orderItems = $em->getRepository('App\Entity\OrderItem')->findBy(['orderRef'=> $order_id]);
        $order = $em->getRepository('App\Entity\Order')->findOneBy(['id'=> $order_id]);
        return $this->render('user/order/items.html.twig', [
            'orderItems' => $orderItems,
            'order' => $order
        ]);
    }
}

src/Controller/User/ShopController.php
<?php

namespace App\Controller\User;

use App\Entity\Gallery;
use App\Entity\Product;
use App\Entity\Category;
use App\Form\AddToCartType;
use App\Repository\ProductRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use App\Manager\CartManager;

class ShopController extends AbstractController
{
    #[Route('/shop', name: 'app_shop')]
    public function index(ManagerRegistry $doctrine): Response
    {
        $em = $doctrine->getManager();
        $repo = $em->getRepository(Product::class);
        $products = $repo->findProductShop();
        $categories = $doctrine
            ->getRepository('App\Entity\Category')
            ->findAll();
        return $this->render('user/shop/index.html.twig', [
            'products' => $products, 'categories' => $categories
        ]);
    }
    #[Route('/shop/details/{id}', name: 'shop_details')]
    public function showAction(ManagerRegistry $doctrine, Request $request, $id, Product $product,CartManager $cartManager): Response
    {
        $form = $this->createForm(AddToCartType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $item = $form->getData();
            $item->setProduct($product);

            $cart = $cartManager->getCurrentCart();
            $cart
                ->addItem($item)
                ->setUpdatedAt(new \DateTime());

            $cartManager->save($cart);

            return $this->redirectToRoute('shop_details', ['id' => $product->getId()]);
        }

        $product = $doctrine
            ->getRepository('App\Entity\Product')
            ->find($id);
        $em = $doctrine->getManager();
        $repo = $em->getRepository(Gallery::class);
        $galleries = $repo->findByProduct($id);
        return $this->render('user/shop/details.html.twig', [
            'product' => $product, 'galleries' => $galleries, 'form' => $form->createView()
        ]);
    }
    #[Route('/shop/{category_id}', name: 'shop_filter')]
    public  function filterProductAction(ManagerRegistry $doctrine ,$category_id):Response
    {
        $em = $doctrine->getManager();
        $repo = $em->getRepository(Product::class);
        $products = $repo->filterProductShop($category_id);
        $categories = $doctrine->getRepository('App\Entity\Category')->findAll();
        return $this->render('user/shop/index.html.twig', ['products' => $products,
            'categories'=>$categories]);
    }
}

templates/user/shop/details.html.twig
{% extends 'user/base.html.twig' %}
{% block title %}
	{{product.name}}
{% endblock %}
{% block body %}
	<!-- Product Details Start -->
	<section class="product_details">
		<div class="container">
			<nav aria-label="tbs-breadcrumb breadcrumb">
				<ol class="breadcrumb">
					<li class="breadcrumb-item">
						<a href="{{ path('app_landing_page') }}">Home</a>
					</li>
					<li class="breadcrumb-item">
						<a href="{{ path('app_shop') }}">Shop</a>
					</li>
					<li class="breadcrumb-item active" aria-current="page">
						{{product.name}}
					</li>
				</ol>
			</nav>
			<div class="tbs-product-details row">
				<div class="col-12 col-md-5">
					<div id="details__carousel" class="carousel slide" data-ride="carousel">
						<div class="carousel-inner">
							{% for gallery in galleries %}
								{% if loop.index == 1 %}
									<div class="carousel-item active">
									{% else %}
										<div class="carousel-item">
										{% endif %}
										<img src="{{asset('uploads/'~gallery.thumbnail)}}" class="d-block w-100" alt="..."/>
									</div>
								{% endfor %}
							</div>
							<button class="carousel-control-prev border-0 bg-transparent" type="button" data-target="#details__carousel" data-slide="prev">
								<span class="carousel-control-prev-icon" aria-hidden="true"></span>
								<span class="sr-only">Previous</span>
							</button>
							<button class="carousel-control-next border-0 bg-transparent" type="button" data-target="#details__carousel" data-slide="next">
								<span class="carousel-control-next-icon" aria-hidden="true"></span>
								<span class="sr-only">Next</span>
							</button>
						</div>
					</div>
					<div class="col-12 col-md-6">
						<div class="details__summary">
							<h1 class="product__title">{{product.name}}</h1>
							<p class="product__price">{{product.listPrice}} đ</p>
							<div class="details__addCart">
								{% if is_granted("IS_AUTHENTICATED_FULLY") %}
									{{ form_start(form) }}
									<div class="single-addtocart-wrapper">
										<div class="quantity">
											<a href="#" class="quantity-minus" role="button">-</a>
											{{ form_widget(form.quantity, {
												'attr': {
													'class': 'form-control qty' ~ (form.quantity.vars.valid ? '' : 'is-invalid'),
													'value': 1,
													'title': 'Qty',
													'size': 4,
													'min': 1
												}
											}) }}
											<a href="#" class="quantity-plus" role="button">+</a>
										</div>
										{{ form_widget(form.add, {'attr': {'class': 'add-to-cart-btn'}})}}
									</div>
									{{ form_end(form) }}
								{% else %}
									<div class="single-addtocart-wrapper">
										<div class="quantity">
											<a href="#" class="quantity-minus" role="button">-</a>
											<input type="number" id="add_to_cart_quantity" class="form-control qty" value="1" title="Qty" size="4" min="1" inputmode="numeric" autocomplete="off"/>
											<a href="#" class="quantity-plus" role="button">+</a>
										</div>
										<button type="submit" name="add-to-cart" class="add-to-cart-btn" onclick="location.href='{{path('app_login')}}'">ADD TO CART</button>
									</div>
								{% endif %}
							</div>
							<hr class="divider"/>
							<div class="details__meta">CATEGORY:
								{{product.category.name}}</div>
						</div>
					</div>
				</div>
				<div class="details__tabs">
					<nav>
						<div class="nav nav-tabs mb-5" id="nav-tab" role="tablist">
							<button class="nav-link active" id="nav-desc-tab" data-toggle="tab" data-target="#nav-desc" type="button" role="tab" aria-controls="nav-desc" aria-selected="true">
								Description
							</button>
							<button class="nav-link" id="nav-ingredient-tab" data-toggle="tab" data-target="#nav-ingredient" type="button" role="tab" aria-controls="nav-ingredient" aria-selected="false">
								Ingredient
							</button>
						</div>
					</nav>
					<div class="tab-content" id="nav-tabContent">
						<div class="tab-pane fade show active" id="nav-desc" role="tabpanel" aria-labelledby="nav-desc-tab">{{product.about}}
						</div>
						<div class="tab-pane fade" id="nav-ingredient" role="tabpanel" aria-labelledby="nav-ingredient-tab">
							{{product.ingredient}}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Product Details End -->
{% endblock %}

templates/user/shop/index.html.twig
{% extends 'user/base.html.twig' %}
{% block title %}TheBeautyStore Shop{% endblock %}
{% block body %}
	<!-- Shop Start -->
	<section class="tbs-shop">
		<div class="tbs__title">
			<h3>Shop</h3>
		</div>
		<div class="product__list">
			<div class="container">
				<div class="row">
					<div class="col-12 col-md-2">
						<div class="tbs-sidebar">
							<div class="tbs-sidebar-item">
								<h3 class="filter__heading">Category</h3>
								<ul>
									<li>
										{% for category in categories %}
											<a href="{{ path('shop_filter', {'category_id': category.id}) }}">{{ category.name }}</a>
										{% endfor %}
									</li>
								</ul>
							</div>
						</div>
					</div>
					<div class="col-12 col-md-10">
						<div class="row">
							{% for product in products %}
								<div class="col-12 col-md-6 col-lg-4">
									<div class="card border-0" style="width: 18rem">
										<div class="card__img">
											<img src="{{asset('uploads/'~product.thumbnail)}}" class="card-img-top" alt="{{product.name}}"/>
											<div class="card__overlay">
												<div class="card__nav">
													<a href="{{ path('shop_details', {'id': product.id}) }}" class="mr-4">
														<i class="fa fa-eye"></i>
													</a>
													<a {% if is_granted("IS_AUTHENTICATED_FULLY") %}href="{{ path('app_user_cart') }}"{% else %}href="{{path('app_login')}}"{% endif %}>
														<i class="fa fa-shopping-cart"></i>
													</a>
												</div>
											</div>
										</div>
										<div class="card__info card-body text-center">
											<a href="{{ path('shop_details', {'id': product.id}) }}" class="card-title font-weight-lighter">
												{{product.name}}
											</a>
											<p class="card-text font-weight-bold">{{product.list_price}} đ</p>
										</div>
									</div>
								</div>
							{% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!-- Shop End -->
{% endblock %}